GameName: Schiffe versenken
Credits: Präsentiert von Projektgruppe AFP
GameDescription: 
LinkHome: Zurück zur Startseite
StartPlacing: Schiffe platzieren
FireShot: Schuss abfeuern!
Won: Du hast gewonnen!
Lost: Du hast verloren.
Drawn: Unentschieden!
PlaceShips: Platziere deine Schiffe
AvailableShips: Verfügbare Flotte
NoPossiblePlacement: Es ist keine vollständige Flottenbelegung möglich.

InputAgainWhenHit: bei Treffer erneut schießen
InputMove: Schiffe verschiebbar
InputDevMode: Entwicklermodus
AdjustRules: Die Regeln anpassen
Rules: Regeln

ShipLength: Länge
ShipsAvailable: Verfügbar
ShipsTotal: Total
ResetFleet: Flotte zurücksetzen
PlaceRandom: Zufällig
StartPlaying: Los!
SkipMove: Ziehen überspringen
MoveShip: Bewege eins deiner Schiffe
YourFleet: Deine Flotte
OpponentsFleet: Gegnerische Flotte
OpponentRemainingShips: Folgende Schiffe musst du noch finden
ShipsUnsunk: Noch nicht gesunken
Hints: Hinweise

Legend: Legende
LegendShipWithArrow: Schiff durch Klick bewegen
LegendShipMovable: Bewegliches Schiff
LegendShipImmovable: Unbewegliches Schiff
LegendShipHit: Treffer
LegendShipSunk: Treffer, Versenkt
LegendFogOfWar: Nicht kartografierter Bereich
LegendWater: Wasser
LegendLastShot: Feindliche Schüsse des letzten Zugs

ConfirmLeave: Wirklich zurück zur Startseite?
About: Über das Spiel
HowToPlay: So wird gespielt
HowToPlaceShipsHeading: Schiffe platzieren
HowToPlaceShipsFull: Zu Beginn des Spiels platzierst du deine Schiffe. Dafür drückst du die linke Maustaste im ersten der Felder, die dein Schiff belegen soll, und lässt sie im letzten zum Schiff gehörenden Feld wieder los. Um ein Schiff wieder zu entfernen, klick es einfach an; dann kannst du es an einer anderen Stelle platzieren. Die Felder um platzierte Schiffe herum werden ausgegraut, da Schiffe sich nicht berühren dürfen. 
HowToPlayHeading: Schüsse feuern und Schiffe bewegen
HowToPlayFull: Nach dem Platzieren der Schiffe sind abwechselnd du und der Computer an der Reihe. Ein Spielzug besteht aus dem Feuern (du darfst so lange feuern, wie du Schiffe des Gegners triffst) und -optional- dem Bewegen eines unversehrten Schiffes um ein Feld. Zum Feuern klicke einfach auf das Feld, auf das du schießen möchtest. Die unversehrten Schiffe werden besonders hervorgehoben und die, die sich bewegen lassen (wenn also kein Hindernis den Weg blockiert) haben Pfeile an ihren Enden. Klicke auf einen Pfeil, um das zugehörige Schiff zu bewegen. Wichtig ist dabei: Gesunkene Schiffe verschwinden! Sobald ein Schiff also komplett versenkt wurde, kann man andere Schiffe darüber hinweg bewegen. 
ReallyFair: Spielt der Computer fair?
ReallyFairFull: Ja, tut er - Er platziert seine Schiffe nach den selben Regeln wie du und erhält auch keine Informationen über deine Schiffe. Bei unserem Spiel gibt es einen 'Mittelmann', der das Spiel leitet. Genau wie du sucht sich der Computer in seinem Zug aus, auf welches Feld er schießen möchte und teilt dies dem Mittelmann mit. Die einzige Information, die er dem Computer zurückgibt, ist die, ob der Schuss ein Schiff getroffen bzw. versenkt hat oder nicht. Ebenso kann der Computer nicht über seine eigenen Schiffe 'lügen', denn auch deine Schüsse werden an den Mittelmann weitergeleitet, der genau weiß, an welchen Stellen die Schiffe des Computers momentan liegen. Am Ende des Spiels siehst du eine animierte Zusammenfassung des Spielablaufs, um nachzuvollziehen, wann welches Schiff wo stand und wann wohin geschossen wurde. 