GameName: Battleships
Credits: Brought to you by Projektgruppe AFP
GameDescription: 
LinkHome: Go home
StartPlacing: Start placing your fleet
FireShot: Fire a shot!
Won: You Won!
Lost: You Lost.
PlaceShips: Place your Ships
AvailableShips: Available Ships
NoPossiblePlacement: There is no possible ship placement.

InputAgainWhenHit: shoot again when hit
InputMove: allow ship movement
InputDevMode: enable developer mode
AdjustRules: Adjust the rules
Rules: Rules

ShipLength: Length
ShipsAvailable: Available
ShipsTotal: Total
ResetFleet: Reset Fleet 
PlaceRandom: Random
StartPlaying: Ready!
SkipMove: Skip moving
MoveShip: Move one of your ships
YourFleet: Your Fleet
OpponentsFleet: Opponent's Fleet
OpponentRemainingShips: These ships are yet to be found
ShipsUnsunk: Not yet sunk
Hints: Hints

Legend: Legend
LegendShipWithArrow: click to move the ship
LegendShipMovable: movable ship
LegendShipImmovable: immovable ship
LegendShipHit: hit
LegendShipSunk: hit and sunk
LegendFogOfWar: undiscovered area
LegendWater: water
LegendLastShot: enemy's last shot

ConfirmLeave: Do you really want to go home?
